usb2642i2c: Do not create if device node does not exist
Opening the device node with 'w+b' works fine, if the defined
/dev/sg -node acutally exists. If it does not exist and the user has
sufficient permissings opening with 'w+b' will create a file in /dev/.
Subsequent calls of usbsdmux with this file will then lead to the
following error:
> OSError: [Errno 25] Inappropriate ioctl for device

Using 'r+b' prevents the file from being created but still allows us to
call ioctls on this file.

Signed-off-by: Chris Fiege <cfi@pengutronix.de>